const translations = {
  fr: {
    starters: "ENTRÉES",
    hot_dishes: "PLATS CHAUDS",
    sides: "GARNITURES",
    hot_drinks: "BOISSON CHAUDES",
    drinks: "BOISSON",
    beer: "BIERRE",
    wine: "VIN & CHAMPAGNE",
    sandwich: "SANDWICH & FAST-FOOD",
    pastry: "PÂTISSERIE & VENOISERIE",
    ice_cream: "GLACE",
    vegetarien: "PLATS VEGETARIENS",
    pates_sauce: "PÂTES ET SAUCES",
    dessert: "DESSERT",
    title_salade1: "SALADE DU MARCHÉ",
    title_salade2: "SALADE FERMIERE",
    title_salade3: "SALADE DE TOMATES MOZZARELLA",
    desc_salade3: "( tomate, fromage, mozzarella bufala, sauce pesto )",
    title_salade4: "SALADE D'AVOCAT AUX CREVETTES",
    desc_salade4: "( Avocat, crevettes, sauce aurore )",
    title_salade5: "SALADE DE BLANC DE VOLAILLE EN BLANQUETTES",
    desc_salade5: "( Blanc de volaille, fond blanc de volaille à la crème )",
    title_salade6: "SALADE DE POMMES DE TERRE AUX GESIER",
    title_salade7: "SALADE DESTENAVE",
    desc_salade7: "( Blanc d'œuf en omelette, tomate amandée, œuf de caille, salade sucrine, amandes, gésier confit, tomates cerise, pousse de soja, olive noire, cornichon, jambon )",
    title_soupe1: "SOUPE À L'OIGNON",
    title_soupe2: "SOUPE AUX LÉGUMES",
    desc_soupe2: "( Légumes en potage )",
    title_quiche: "QUICHE LORRAINE ET SA SALADE",
    desc_quiche: "( pâte brisée, sauce quiche, jambon de bœuf )",
    title_bouche: "BOUCHE À LA REINE AU POULET/CREVETTE",
    desc_bouche: "( croûte vide, pâte feuilletée de poulet ou de crevette, sauce cream )",
    title_akpessi: "AKPESSI MERVEILLE GOLDEN",
    desc_akpessi: "( Igname vapeur, émincé de thon ou maquereau, aubergine locale )",
    title_gambas: "POÊLÉE DE GAMBAS AUX LÉGUMES CROQUANTS",
    desc_gambas: "( Gambas, carotte, courgette, poivron, oignon, tomate )",
    title_alloco: "ALLOCO",
    title_attieke: "ATTIEKE",
    title_riz: "RIZ BLANC",
    title_pomme_sautee: "POMME SAUTÉE",
    title_frite_igname: "FRITE D'IGNAME",
    title_legumes: "ASSORTIMENT DE LÉGUMES",
    title_salade_pate: "SALADE DE PÂTE AUX LÉGUMES PISTOU",
    title_veloute: "VELOUTÉ DE LÉGUMES",
    title_lentille: "LENTILLES À LA MAROCAINE",
    title_riz_legumes: "RIZ SAUTÉ AUX LÉGUMES",
    title_julienne: "JULIENNE DE LÉGUMES AU BEURRE DOUX",
    beer_press: "BIERRE PRESSION",
  heineken: "HEINEKEN",
  desperados: "DESPERADOS",
  ivoire: "IVOIRE",
  beaufort: "BEAUFORT",
  smirnoff: "SMIRNOFF",
  doppel: "DOPPEL MUNICH",
  lager: "DOPPEL MUNICH LAGER",
  rhino: "RHINO",
  guiness: "GUINESS",
  cafe_l:"CAFE AU LAIT",
  cafe_s:"CAFE SIMPLE ",
  nescafe:"NESCAFE",
  decafeine:"DECAFEINE",
  cappuccino:"CAPPUCCINO",
  grog:"GROG",
  chocolat:"CHOCOLAT CHAUX",
  lait:"LAIT CHAUT",
  eau_minerale_05l: "EAU MINERALE 0.5L",
    eau_minerale_15l : "EAU MINERALE 1.5L",
    jus_de_citron: "JUS DE CITRON",
    jus_d_ananas: "JUS D'ANANAS",
    jus_de_bissap: "JUS DE BISSAP",
    jus_de_pasteque: "JUS DE PASTEQUE",
    jus_de_pamplemouse: "JUS DE PAMPLEMOUSE",
    jus_d_orange: "JUS D'ORANGE",
    jus_de_gimgimbre: "JUS DE GIMGIMBRE",
    coca_cola: "COCA COLA",
    coca_cola_zero: "COCA COLA ZERO",
    sprite: "SPRITE",
    fanta_orange: "FANTA ORANGE",
    orangina: "ORANGINA",
    youki: "YOUKI",
    tequila: "TÉQUILA",
    tonic: "TONIC",
    codys: "CODY'S",
    youzou: "YOUZOU",
    fromage:"ASSIETTE DE FROMAGE ASSORTIE",
    tarte:"TARTE AU CHOCOLAT",
    Moelleux:"MOELLEUX AU CHOCOLAT",
    salade_fruit:"SALADE DE FRUITS",
    creme:"CREME BRULEE",
    assiette:"ASSIETE DE FRUIT DE SAISON",
    macaroni:"MARCARONI: TAGLATELLE/PENNE/SPAGHETTI",
    CORNET_2_BOULES:"CORNET 2 BOULES",
    COUPE_DE_GLACES_CREME_CHANTILLY:"COUPE DE GLACES CREME CHANTILLY",

  },
  en: {
    starters: "STARTERS",
    hot_dishes: "HOT DISHES",
    sides: "SIDES",
    hot_drinks: "HOT DRINKS",
    drinks: "DRINKS",
    beer: "BEER",
    wine: "WINE & CHAMPAGNE",
    sandwich: "SANDWICH & FAST-FOOD",
    pastry: "PASTRY & BAKERY",
    ice_cream: "ICE CREAM",
    vegetarien: "VEGETARIAN DISHES",
    pates_sauce: "PASTA AND SAUCE",
    dessert: "DESSERT",
    title_salade1: "MARKET SALAD",
    title_salade2: "FARMER SALAD",
    title_salade3: "TOMATO MOZZARELLA SALAD",
    desc_salade3: "( tomato, cheese, mozzarella bufala, pesto sauce )",
    title_salade4: "AVOCADO SALAD WITH SHRIMP ",
    desc_salade4: "( Avocado, shrimp, aurora sauce )",
    title_salade5: "BLANQUETTE POULTRY BREAST SALAD",
    desc_salade5: "( poultry breast, breast with cream )",
    title_salade6: "GIZZARD POTATO SALAD",
    title_salade7: "DESTENAVE SALAD",
    desc_salade7: "( Egg white in omelet, blanched tomato, quail egg, sucrine salad, almonds, condied gizzard, cherry tomatoes, soybean sprouts, black olive, pickles, ham )",
    title_soupe1: "ONION SOUP",
    title_soupe2: "VEGETABLE SOUP",
    desc_soupe2: "( Vegetable potage )",
    title_quiche: "QUICHE LORRAINE WITH SALAD",
    desc_quiche: "( shortcrust pastry, quiche sauce, beef ham )",
    title_bouche: "CHICKEN/SHRIMP ",
    desc_bouche: "( puff pastry shell, chicken or shrimp, cream sauce )",
    title_akpessi: "AKPESSI GOLDEN SPECIAL",
    desc_akpessi: "( Steamed yam, cumbled turn or mackerel, local eggplant )",
    title_gambas: "FRIED PAWN GAMBAS WITH CRUNCHY VEGETABLES",
    desc_gambas: "( Gambas, carrot, zucchini, pepper, onion, tomato )",
    title_alloco: "ALOCO",
  title_attieke: "ATTIEKE",
  title_riz: "WHITE RICE",
  title_pomme_sautee: "SAUTÉED POTATOES",
  title_frite_igname: "YAM FRIES",
  title_legumes: "VEGETABLE MIX",
  title_salade_pate: "PASTA SALAD WITH VEGETABLES",
  title_veloute: "VEGETABLE VELVET SOUP",
  title_lentille: "MOROCCAN LENTILS",
  title_riz_legumes: "FRIED RICE WITH VEGETABLES",
  title_julienne: "VEGGIE JULIENNE WITH BUTTER",
  beer_press: "DRAFT BEER",
  heineken: "HEINEKEN",
  desperados: "DESPERADOS",
  ivoire: "IVOIRE",
  beaufort: "BEAUFORT",
  smirnoff: "SMIRNOFF",
  doppel: "DOPPEL MUNICH",
  lager: "DOPPEL MUNICH LAGER",
  rhino: "RHINO",
  guiness: "GUINNESS",
  cafe_l:"LATTE",
  cafe_s:"SINGLE COFFEE ",
  nescafe:"NESCAFE",
  decafeine:"DECAF",
  cappuccino:"CAPPUCCINO",
  grog:"GROG",
  chocolat:"CHOCOLATE LIME",
  lait:"LIME MILK",
  eau_minerale_05l: "MINERAL WATER 0.5L",
    eau_minerale_15l: "MINERAL WATER 1.5L",
    jus_de_citron: "LEMON JUICE",
    jus_d_ananas: "PINEAPPLE JUICE",
    jus_de_bissap: "HIBISCUS JUICE",
    jus_de_pasteque: "WATERMELON JUICE",
    jus_de_pamplemouse: "GRAPEFRUIT JUICE",
    jus_d_orange: "ORANGE JUICE",
    jus_de_gimgimbre: "GINGER JUICE",
    coca_cola: "COCA COLA",
    coca_cola_zero: "COCA COLA ZERO",
    sprite: "SPRITE",
    fanta_orange: "FANTA ORANGE",
    orangina: "ORANGINA",
    youki: "YOUKI",
    tequila: "TEQUILA",
    tonic: "TONIC",
    codys: "CODY'S",
    youzou: "YOUZOU",
    fromage:"ASSORTED CHEESE PLATE",
    tarte:"CHOCOLATE PIE",
    Moelleux:"CHOCOLATE MOELLEUX",
    salade_fruit:"FRUIT SALAD",
    creme:"BURNT CREAM",
    macaroni:"MARCARONI: TAGLATELLE/PENNE/SPAGHETTI",
    assiette:"PLATE OF SEASONAL FRUIT",
    CORNET_2_BOULES:"2-BALL CONE",
    COUPE_DE_GLACES_CREME_CHANTILLY:"ICE CREAM CHANTILLy CUP",
    COUPE_DE_GLASSE_3_BOULES:"GLASS CUP 3 BALLS",
    COUPE_DE_GLASSE_ET_SORBET:"GLASS AND SORBET CUP",
    choco:"(CHOCOLATE, MALAGA, STRAWBERRY, AMERICAN, MINT, RASPBERRY, PLUMBER, COFFEE, SMAT)",
    bolognaise:"BOLOGNESE SAUCE",
    carbonara:"CARBONARA SAUCE",
    pain_chocolat:"chocolate croissant",
    pain_raisin:"RAISIN BREAD",
    darne_merou:"SNAKE GROUPER STEAK WITH MANTAISE",
    carpe_braisée:"BRAISED CARPE",
    accompagnement:"ATTIEKE/ALLOCO/YAM FRIES",
    carpe_frit:"FRIED CARPE",
    rice:"ATTIEKE/RICE",
    poulet_braise:"BRAISED CHICKEN",
    poulet_frit:"FRIED CHICKEN",
    kedjenou_poulet:"KEDJENOU OF CHICKEN",
    gambas:"PRAWNS",
    pintade_braise:"BRAISED GUINEA FOWL",
    kedjenou_pintade:"GUINEA FOWL KEDJENOU",
    fillet_boeuf:"BEEF FILLET",
    brochette:"SKEWERS TOGETHER SAMANDJE/ALLOCO",
    samandje:"(grouper, onion, tomato, pepper, prawns)",
    sole_meuniere:"SOLE MEUNIÈRE/APPLE PARSLEY",
    sole_braise:"BRAISED FLOOR",
    sole_frit:"FRIED SOL",
    fillet_merou:"GROUPER FILLET",
    langouste:"GRILLED COBSTER WITH GRIBISHE SAUCE/POTATO-FRIES",
    petit_capi:"SMALL CAPTAIN",
    calalar_saute:"SAUTED SQUID WITH FINE HERBS/SAUTEED VEGETABLE",
    calamar:"SQUID",
    gogot:"LEG OF LAMB",
    fillet_boeuf:"FILLET OF BEEF/ROSETTE OF BEEF",
    smv:"(WINE MERCHAND SAUCE,SAUTE VEGETABLE)",
    souris_d_agneau:"LAMB SHANK WITH BORDELAISE",
    pure_de_pomme:"MASHED POTATOES",
    carre_dagneau:"MARK OF CAMB WITH TAPENADE/GREEN BEANS AND GARLIC",
    lapin_creme:"SAUTEED RABBIT WITH CREAM MUSHROOM SAUCE/RICE PILAF",
    lapin_braise:"BRAISED RABBIT",
    cailles_farcie:"STUFFED QUAIL TWO FLAVORS/CURLY APPLE",
    kedjenou_lapin:"KEDJENOU OF RABBIT",
    entrecote_de_boeuf:"BEEF RIB STEAK",
    tacos_viande:"MEAT TACOS",
    tacos_poulet:"CHICKEN TACOS",
    risoto:"MUSHROOM RISOTO",
    soupe_carpe:"CARP SOUP",
    




  
  }
};

//const { translations } = require("./translations");

  function applyTranslations(lang) {
    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const langSelect = document.getElementById("langSelect");
    if (langSelect) langSelect.value = lang;
}

// Exécuter automatiquement au chargement de la page
window.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("lang") || "fr";
    applyTranslations(savedLang);

    const langSelect = document.getElementById("langSelect");
    if (langSelect) {
        langSelect.addEventListener("change", function () {
            const newLang = this.value;
            localStorage.setItem("lang", newLang);
            applyTranslations(newLang);
        });
    }
});


/*document.addEventListener("DOMContentLoaded", () => {
  const lang = localStorage.getItem("lang") || "fr";
  applyTranslations(lang);
});*/
